version: '3.8'
services:
  app:
    container_name: rbac-app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    env_file:
      - .env